const quotes = [
  { content: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "Happiness depends upon ourselves.", author: "Aristotle" },
  { content: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { content: "You do not find the happy life. You make it.", author: "Camilla Eyring Kimball" },
  { content: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { content: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { content: "Nothing will work unless you do.", author: "Maya Angelou" },
  { content: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { content: "If you’re going through hell, keep going.", author: "Winston Churchill" },
  { content: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { content: "Great things never came from comfort zones.", author: "Unknown" },
  { content: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { content: "Failure is not the opposite of success; it’s part of success.", author: "Arianna Huffington" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { content: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { content: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" }
];

export default quotes;
